### ISSUE TITLE
Can't Control Appstore

### ISSUE THREAD

**Issue by sumbodyshero** [fortheusers/hb-appstore#10]
My controllers and touchscreen work fine, but they stop working when I am in the Appstore. The only thing I can do is press A to download the default selected item, or hit the Home button. Please help!

**Comment by vgmoose** [comment]
What joycon/jig configuration are you using? Also docked/undocked and what firmware?

It might be related to this: https://gbatemp.net/threads/switch-homebrew-appstore.493086/page-8#post-7984538

**Comment by bbrks** [comment]
Undocking my controller worked for me! Thanks 👍

**Comment by vgmoose** [comment]
I'm still curious what causes this, for me it's able to work docked or undocked.

What's the total setup of the switch (firmware, controllers connected) when it's not working?

**Comment by vgmoose** [comment]
I think this is fixed on master, but if people are still experiencing the issue in 2.0, let me know

**Comment by withers666** [comment]
I am having same issue in Hb app store controllers stop working properly

**Comment by ArchiFleKs** [comment]
same issue

**Comment by The-Original-Ricky-Tang** [comment]
*BUMP*

same issue
running version 2.1

**Comment by Kauzinn** [comment]
same issue

**Comment by vgmoose** [comment]
People that are still having input problems are likely hitting #54 

Here's a WIP build to help diagnose issues: 
[appstore.nro.zip](https://github.com/vgmoose/hb-appstore/files/3897912/appstore.nro.zip)

Can someone say if the input problem resolved?

**Comment by joshuajaharwood** [comment]
> 
> 
> People that are still having input problems are likely hitting #54
> 
> Here's a WIP build to help diagnose issues:
> [appstore.nro.zip](https://github.com/vgmoose/hb-appstore/files/3897912/appstore.nro.zip)
> 
> Can someone say if the input problem resolved?

Linked build fixes the issue for me. Much appreciated
