### ISSUE TITLE
Loading stuck, cache fail

### ISSUE THREAD

**Issue by prankard** [fortheusers/hb-appstore#13]
When loading the appstore-nx on switch 5.0.2 (AppStore 1.0.0). It gets stuck on the loading.
Deleting the tmp directory made the appstore work again, but before I backed-up the offending cache.

Please find the backup here:
https://ufile.io/neck6

Hopefully you can use this to re-create the issue.

I've also been having issues downloading/booting apps on the appstore, where the app fails to boot. But when when I download via the website on Chrome and unpack manually to the device the app works.

Perhaps it might be my dodgy SD card too.

**Comment by jslay88** [comment]
I am seeing the same issue.

**Comment by vgmoose** [comment]
I think that I have fixed this issue on master, alongside switching to SDL2 from SDL1, but the touch input still isn't working, so I haven't done another appstore release yet.

@jslay88 if you still have your cache folder, would you be able to share it as well?

Using prankard's cache files, I was able to reproduce the crash on the 1.0 release and no longer on master, but it may be possible that there are different ways for it to become corrupted.

**Comment by jslay88** [comment]
I do not. But, after having removed it once, I haven't had the issue since.

**Comment by Poincare1** [comment]
I have this issue as well, stuck as loading.  Deleting the app/directory from SD card and copying back to try again does nothing.  Still stuck at loading.  Is there a fix?

**Comment by vgmoose** [comment]
Should be resolved on master! With the files that people presented I was no longer able to reproduce a crash.

Just in case, I added a "clear icon cache" to the settings page (although it won't do much good if the user can't boot in the first place). Maybe holding L+R before loading should activate the clear icon cache function (like in wiiu-hbas)
