### ISSUE TITLE
Can't open appstore, it's stuck on the initial loading screen

### ISSUE THREAD

**Issue by aforty** [fortheusers/hb-appstore#16]
Nothing ever moves on the loading screen, just sits there and never goes anywhere. My sd card is formatted with exfat, is that the issue?

Here is my directory structure from the root.

![screen shot 2018-07-11 at 11 26 50 am](https://user-images.githubusercontent.com/523683/42582513-56371a96-84fd-11e8-9521-74f7155d8b3a.png)

**Comment by vgmoose** [comment]
Usually this issue means the switch is offline. Can you try a connection test in the Switch system settings? If that doesn't work, is ftpd able to use networking?

**Comment by vgmoose** [comment]
(if it is that, then I need to do #9)

**Comment by aforty** [comment]
Ah ok, yeah not sure what I thought was going to happen when opening a app store in airplane mode. Not sure I want to risk going online just yet but thanks for the clarification.
