### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by shyim** [fortheusers/hb-appstore#18]
I am trying to compile the app store and get always the error
```
/opt/devkitpro/libnx/include/switch/services/audren.h: In function 'constexpr size_t audrenGetOutputParamSize(const AudioRendererConfig*)':
/opt/devkitpro/libnx/include/switch/services/audren.h:318:1: error: body of 'constexpr' function 'constexpr size_t audrenGetOutputParamSize(const AudioRendererConfig*)' not a return-statement
```

I am new with libnx :see_no_evil:

**Comment by vgmoose** [comment]
Looks like a change from the latest (1.4.0) libnx release. [This answer](https://stackoverflow.com/a/45097262) suggests that it has to do with multi-line bodies of a constexpr function only being allowed in C++14.

I've made a change to use `-std=gnu++14` in the Makefile, which should resolve the issue. Thanks for the report!
