### ISSUE TITLE
Use libcurl instead of hacky HTTP download code

### ISSUE THREAD

**Issue by vgmoose** [fortheusers/hb-appstore#2]
In [Utils.cpp](https://github.com/vgmoose/get/blob/master/src/Utils.cpp#L105-L167), on Switch targets, libcurl isn't able to be used. This results in slower, unreliable http download code.

**Comment by vgmoose** [comment]
There's a libcurl portlib available on dkp-pacman, but using it results in the following compilation error:
```
/opt/devkitpro/portlibs/switch/lib/libcurl.a(libcurl_la-mime.o): In function curl_mime_filedata':
mime.c:(.text+0x1a50): undefined reference toaccess'
/opt/devkitpro/portlibs/switch/lib/libcurl.a(libcurl_la-timeval.o): In function Curl_now':
timeval.c:(.text+0x10): undefined reference toclock_gettime'
collect2: error: ld returned 1 exit status
make[1]:  Error 1
```

**Comment by Black-Seraph** [comment]
What's your problem exactly? Removed the -DNOCURL flag, added -lcurl, and all builds flawlessly and works fine.

**Comment by vgmoose** [comment]
You're right! It used to be crashing my Switch (after resolving the above mentioned build problems) but with the latest libcurl package everything looks good.

Removed NOCURL code from  https://github.com/vgmoose/get/commit/2338da592f3e874cda1f6bd6d060c06327d8dcd7
Updated progress bar to use curl's progress callback: https://github.com/vgmoose/appstorenx/commit/023373a60040ab45edb4e882c8f58232f74be86a
