### ISSUE TITLE
[wiiu] can't exit with home button

### ISSUE THREAD

**Issue by vgmoose** [fortheusers/hb-appstore#28]
On PC and Wii U, the +/start/enter button can be used to exit the app, but on switch this is ignored, as if the button never fires. It could be a misalignment between the SDL2 gamepad controls between Switch and Wii U.

If it's really just the start button behavior is different, maybe it should be moved to a different button

**Comment by Continous** [comment]
Perhaps an exit button in the actual interface would be useful.

**Comment by vgmoose** [comment]
Added exit using the minus button, but now on Wii U, we ironically can't exit with home any more.

Also agree that a UI exit element would be useful

**Comment by vgmoose** [comment]
Exit added in 2.2, waiting on a solution from wiiu-sdl2 on firing a home button event for us to process and exit

**Comment by vgmoose** [comment]
(meant to leave open, awaiting wiiu sdl2 improvements)

**Comment by vgmoose** [comment]
proc UI and home button support has been added (thanks to @Maschell) to master)next release will include this fix.
