### ISSUE TITLE
Cannot compile Wii U version: Packages not found

### ISSUE THREAD

**Issue by BullyWiiPlaza** [fortheusers/hb-appstore#37]
I downloaded the devkitPro `devkitpro-pacman.deb` and installed it with `dpkg -i devkitpro-pacman.deb`.

````
ubuntu@ubuntu:/opt/devkitpro/pacman/bin$ sudo ./pacman -S wut-linux wiiu-sdl2 devkitPPC wiiu-libromfs wiiu-sdl2_gfx wiiu-sdl2_image wiiu-sdl2_ttf wiiu-sdl2_mixer ppc-zlib ppc-bzip2 ppc-freetype ppc-libpng ppc-mpg123 wiiu-curl-headers ppc-pkg-config wiiu-pkg-config
error: target not found: wut-linux
error: target not found: wiiu-sdl2
warning: devkitPPC-r35-1 is up to date -- reinstalling
error: target not found: wiiu-libromfs
error: target not found: wiiu-sdl2_gfx
error: target not found: wiiu-sdl2_image
error: target not found: wiiu-sdl2_ttf
error: target not found: wiiu-sdl2_mixer
error: target not found: wiiu-curl-headers
warning: wiiu-pkg-config-0.28-2 is up to date -- reinstalling
````

**Comment by CreeperMario** [comment]
Did you add fling to your package repositories? https://gitlab.com/QuarkTheAwesome/wiiu-fling#installing

**Comment by vgmoose** [comment]
I also think fling is missing here, but correct me if I'm wrong or there are issues with that.

This is the script travis is using to setup the dkP + fling repos: https://github.com/vgmoose/hb-appstore/blob/master/dependency_helper.sh#L27-L40

last travis build: https://travis-ci.org/vgmoose/hb-appstore/jobs/520638012

**Comment by vgmoose** [comment]
I should also add that if `wut-linux` isn't working, you'll need to export WUT_ROOT yourself, such as:

```
export WUT_ROOT=/opt/devkitpro/wut
```
