### ISSUE TITLE
Outdated apps can't be removed

### ISSUE THREAD

**Issue by CodingKoopa** [fortheusers/hb-appstore#39]
When opening the details for an app that is outdated, HBAS shows "(A) Update)" and "(B) Cancel", but nothing to remove it. Removing an outdated app should be an option.

Tested on Wii U version launched from HBL.

**Comment by vgmoose** [comment]
Definitely agree, probably a carry over from the original switch version where the pop-up only had two options.

**Comment by vgmoose** [comment]
Still important!

The only real concern is sidebar space, as the launch button makes everything cramped as is. Possibly can be added alongside a pop up UI in chesto, then the sidebar can just become simply “Manage” with three options within it: Uninstall, Reinstall, Launch

**Comment by vgmoose** [comment]
Going to track this in [gitlab/hb-appstore#16](https://gitlab.com/4TU/hb-appstore/-/issues/16), alongside other AppDetails changes
