### ISSUE TITLE
Cant install apps

### ISSUE THREAD

**Issue by kozholeks** [fortheusers/hb-appstore#41]
Hey, whenever I try to install and app it says its installing but it never installs and still shows the download icon  and never shows up in a homebrew launcher. Does anyone know why this is happening? My write lock is not enabled on my sd card

**Comment by vgmoose** [comment]
Thanks for the report! Could you tell me about what files (if any) related to hb-appstore exist on your SD card? For instance, in the appstore folders, is there a `.get` folder, and if so, what's inside of it?

Also a few more questions:
Wii U or Switch?
Do the apps in the main list have icons?
Can you download apps from the website? https://fortheusers.org

On Wii U, I have seen similar symptoms when the `appstore` directory is in the wrong place, but I thought I had fixed that issue before releasing. I've also seen something that sounds similar with write lock, but you've already said that's not the case.

**Comment by kozholeks** [comment]
I will see when I get back from my vacation.

**Comment by vgmoose** [comment]
Thanks again, by the way is this for Wii U or Switch?

**Comment by vgmoose** [comment]
any more info on this?

**Comment by kozholeks** [comment]
Nope, I lost my SD card yesterday. Can't even try to use my homebrew anymore.
