### ISSUE TITLE
Cant download apps

### ISSUE THREAD

**Issue by Toolazytochoose** [fortheusers/hb-appstore#42]
I started the homebrew channel 1.4 via Browser and opened the Homebrew Appstore and tried to download Mocha CFW SD by dimok. A white bar, comes up and starts filling up with blue, after the bar is completely filled it throws me back to the Homebrew Appstore 
Please help

**Comment by crc-32** [comment]
This is the intended functionality, do you mean mocha isnt now on your SD after it throws you back to the store?

**Comment by Toolazytochoose** [comment]
No, it isn't

**Comment by vgmoose** [comment]
Did this start just recently? #41 is talking about a similar issue.

After installing, the state of it on the console is still "GET"? Is your SD card write-locked?

**Comment by Toolazytochoose** [comment]
No

**Comment by Toolazytochoose** [comment]
Bruh yes it was, now its working 😅🤦‍♂️
