### ISSUE TITLE
[WII U] WIIMote support

### ISSUE THREAD

**Issue by NiHuShu** [fortheusers/hb-appstore#43]
WiiMote support for Wii U was in earlier versions of app store so why it isn't there now?

**Comment by compucat** [comment]
Regression confirmed; is this an issue of HBAS or SDL?

**Comment by NiHuShu** [comment]
SDL

**Comment by vgmoose** [comment]
Sorry, wasn't intentionally removed, looking into ways to add it back now.

Incidentally, the original HBAS was a fork of Wii U's HBL, so the original wiimote support in the first place was never fully intentional– but definitely should be added back

**Comment by NiHuShu** [comment]
I would be really thankful if you could bring it back

**Comment by vgmoose** [comment]
To my knowledge this is fixed in 2.2, can anyone confirm?

Still it would be nice to have pointer support as well, could also fall in SDL territory

**Comment by vgmoose** [comment]
Closing with the Wii button support added in SDL2.

For further wiimote pointer support on Wii U, it would need to be added to Wii U's SDL2 port first, however. It's worth noting that Wii's SDL and the in-development Wii/vWii port will support this
