### ISSUE TITLE
Help needed: How to add my own repo?

### ISSUE THREAD

**Issue by station7** [fortheusers/hb-appstore#44]
Many thanks for the appstore. I read the documentation of appstore and libget several times, but where do I find repos.json to include my own repo?

**Comment by pwsincd** [comment]
we currently use a python script to semi automate the creation of this , an example being this : https://www.switchbru.com/appstore/repo.json   they can also be manually created.

an example of our py script would be : https://github.com/pwsincd/appstore/blob/master/repo.py

vgmoose will probably give clear instruction :)

**Comment by rw-r-r-0644** [comment]
If you mean where the repos.json file is located, it's in sd:/wiiu/apps/appstore/.get/repos.json for wiiu and sd:/switch/appstore/.get/repos.json for switch

**Comment by station7** [comment]
Thank you so much for your answers - that covers all my questions!

**Comment by station7** [comment]
Okay, I got my own repo up and running, but I have one questions left: hb-appstore does not show icons of my homebrew-apps. How do I add icons? Thanks for helping me out.

SOLVED, I figured it out myself (https://github.com/vgmoose/libget/tree/master/web/packages). Thanks anyway!
