### ISSUE TITLE
Custom Source

### ISSUE THREAD

**Issue by EmptyAirSwap** [fortheusers/hb-appstore#45]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add the possibility to add custom source (like GDrive, DropBox, etc). 
**Example**: I add a .nro file on GDrive, I add the GDrive link on HB AppStore and it easily install the nro

**Platform:**
Nintendo Switch - WiiU

**Comment by vgmoose** [comment]
Probably an app like [nXDownload](https://github.com/Dontwait00/nXDownload) fits this use case, and then [NX-Shell](https://github.com/joel16/NX-Shell/releases) to move the files into the right spot.

Custom sources/repos can be specified in `./repos.json`, but they will have to be generated in a proper [libget](http://gitlab.com/4tu/libget) repo format for app store to parse. This can be done using [Spinarak](https://gitlab.com/4TU/spinarak), but would have to be done in advance + hosted.

The reason for it not being as straightforward as it seems, is the rules for where an NRO should go depend on the app and where they expect to be placed. (Sometimes they are in a folder, sometimes a specific folder, sometimes right in sd:/switch), so as a result, the other information in the repo (which spinarak takes as input) is needed to properly put NROs in the right spot.
