### ISSUE TITLE
Release needs to be recompiled with the latest Libnx for 9.0.0

### ISSUE THREAD

**Issue by TheGinGear** [fortheusers/hb-appstore#48]
**Describe the bug**
As described in the [release notes for the latest version of atmosphere](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.9.4), all homebrew has to be recompiled with the latest version of Libnx to run on 9.0.0.
Currently only the touchscreen works for inputs, all controllers fail to do anything else.
**Platform:**
Switch
**To Reproduce**
Use on firmware 9.0.0

**Comment by vgmoose** [comment]
working on it! thank you for the heads up

Currently we're hitting an issue with newer libnx versions regarding updating ourselves, which will be needed for future updates. Continuing to get this recompiled as soon as possible

**Comment by vgmoose** [comment]
Done in 2.2!
