### ISSUE TITLE
hbas.elf not loading in hbl1.4

### ISSUE THREAD

**Issue by fujingdcn** [fortheusers/hb-appstore#50]
**Package:**
Which app or package on the Store is giving you trouble?

**Describe the problem**
A clear and concise description of what the problem is.

**Platform:**
Is this for the Switch, Wii U, or both versions?

**Comment by vgmoose** [comment]
does it fail consistently from first boot of the console? what's your setup?

**Comment by wariotx** [comment]
Having the same issue, on wiiu 5.5.4 without coldboot.

Everytime it's stuck at about 95%, also tried *.rpx with no success

**Comment by Kilumi** [comment]
I have the same issue, on wii u 5.5.3

**Comment by vgmoose** [comment]
I believe this concern is resolved in 2.2

hbas.elf should be cleaned up on the first run, HBL 1.4 is required to run RPX files going forward

Latest HBL can be found here: https://apps.fortheusers.org/wiiu/homebrew_launcher

If people can replicate it with that build we can re-open
