### ISSUE TITLE
Crashing when downloading hb

### ISSUE THREAD

**Issue by Zexceil** [fortheusers/hb-appstore#52]
**Describe the bug**
HB Appstore crashes when downloading homebrew

**Platform:**
Nintendo Switch
Latest AMS & Hekate 
EmuMMC

**To Reproduce**
1.Use FW 9.0.1 EmuMMC
2.Use Latest AMS & Hekate
3.Launch HB Appstore via Applet mode(I don't have any games on system to launch other way)
4.Attempt to download a homebrew(In my case NXThemes)

**AMS Error: 2168-0002(0x4a8)**

**Comment by a5723797** [comment]
same problems here

**Comment by crc-32** [comment]
See #29, this is much more common in applet mode due to memory constraints so if possible run HB that way, we have been working on mitigating this so it'll be much better by next release.
