### ISSUE TITLE
Nintendo switch  controller help 

### ISSUE THREAD

**Issue by withers666** [fortheusers/hb-appstore#53]
Controller does not work properly when I go into hb app store please help 9.0.0 I am on

**Comment by joshuajaharwood** [comment]
Same issue. Running store version 2.1 on 9.0.0, Atmo 0.9.4, latest Kosmos release. Tried reinstalling to no avail.

Touchscreen controls work, but joycons straight up don't (except the home button).

**Comment by crc-32** [comment]
The appstore hasn't been updated to fix the 9.0 controller bug as doing so would cut it off from self updating forever, once we patch this an update will be released fixing all controls.

**Comment by vgmoose** [comment]
I've posted an NRO that should address this in https://github.com/vgmoose/hb-appstore/issues/10#issuecomment-559169224

**Comment by vgmoose** [comment]
should be fixed on master and in linked build!
