### ISSUE TITLE
Error while opening hb store or installing apps

### ISSUE THREAD

**Issue by D00ZY1** [fortheusers/hb-appstore#55]
**Bug Description:** 
When I go to Hb store I get this https://pasteboard.co/IMcI7h8.jpg 

**Platform:**
Switch

**To Reproduce**
I installed atmosphere normally and installed homebrew normally and when i goto launch I get close to the and i get Error conde:2168-0002 (0x4a8)

**Comment by vgmoose** [comment]
Thanks for the bug report. Does this build address the issue? https://gitlab.com/4TU/hb-appstore/-/jobs/381202959/artifacts/download

**Comment by D00ZY1** [comment]
no problem, but what would i do with this im just getting into homebrewing the switch

**Comment by vgmoose** [comment]
This NRO goes in: `sd:/switch/appstore/appstore.nro` on SD  and should replace the file that’s already there.

After copying and running, it should have a notice that there’s an “update” for hb appstore itself, which you should ignore for now (this is pre-release).

**Comment by D00ZY1** [comment]
ok its fixed
 thank you

**Comment by vgmoose** [comment]
addressed in 2.2 release!

a combination of:
- not loading all icons into memory
- saving files directly to disk
- using icon banners in applet mode
