### ISSUE TITLE
SDL 1.2 original GBATemp post missing important elements

### ISSUE THREAD

**Issue by MarcoDotIO** [fortheusers/hb-appstore#6]
I am having problems building SDL 1.2 with the files I hunted down, mainly from the original author under a different name I would assume. But when I try to build the program, I ended up with this error:
https://pastebin.com/S58sujNb

**Comment by vgmoose** [comment]
Thanks, I'll look into this on a fresh machine. In the mean time the only advice I can give is to try an older commit of SDL-SWITCH.

This app was originally on sdl2, and I see switch-sdl2 is available on devkitPro pacman, so the long term solution might be to just move to that.

**Comment by vgmoose** [comment]
It looks like the devkitPro pacman sdl1.2 package still isn't ready. In the mean time you should be able to use this fork to build this repo: https://github.com/vgmoose/SDL-SWITCH

**Comment by vgmoose** [comment]
There's a new branch ([sdl2](https://github.com/vgmoose/appstorenx/tree/sdl2)) where I started porting it over to sdl2. Right now, it's not drawing images and text on PC, but when it does work then I would expect it to work on the Switch as well. Going forward, this is a better solution that trying to get sdl1.2 working again.

**Comment by vgmoose** [comment]
I pushed some more of what I have for sdl1 -> sdl2 changes to the sdl2 branch: https://github.com/vgmoose/appstorenx/tree/sdl2

There are still some issues with displaying black text, I'm not sure what the issue is. Also, the PC app seems noticeably slower while scrolling so there may be some optimization things that need to be solved

**Comment by AnnsAnns** [comment]
Pretty sure that this issue can be closed since master also uses SDL2 now.

**Comment by vgmoose** [comment]
true, although I am getting font issues still (maybe will move to shared font?) it does work with sdl2 now
