### ISSUE TITLE
switchbru.com appears to be parked by GoDaddy

### ISSUE THREAD

**Issue by EpicLPer** [fortheusers/hb-appstore#60]
Not sure what happened but it seems the switchbru.com as a whole got parked by GoDaddy. Hope it isn't offline forever?

**Comment by vgmoose** [comment]
A temporary issue, thanks for the heads up. Not dead yet!

For the default wiiu/switch repos, we internally have an uptime checker and notifications if it goes down, but adding this status info into the app would be useful. Created [gitlab/hb-appstore#18](https://gitlab.com/4TU/hb-appstore/-/issues/18) for adding this integration.
