### ISSUE TITLE
Wii U | App not popping up on homebrew.

### ISSUE THREAD

**Issue by BlaklavaFx** [fortheusers/hb-appstore#63]
**Describe the bug**
when i try to load up homebrew with it in the apps folder, it doesnt show up.

**Platform:**
Wii U

**To Reproduce**
What I have done was,
i made a folder name "appstore" in the apps folder of the sd card.
i put all of the files into the folder.
and i put my sd card in
and then i loaded homebrew, and it wasnt there please fix this!

**Comment by vgmoose** [comment]
What version of HBL are you using? Can you try with this one? https://apps.fortheusers.org/wiiu/homebrew_launcher

I suspect this is an issue with loading .rpx files

I should also double check that you're putting it in `sd:/wiiu/apps` not just `sd:/apps`

**Comment by vgmoose** [comment]
also: "i put all of the files into the [appstore] folder." Which files? There should just be an RPX, XML, and PNG, no nested folders

**Comment by BlaklavaFx** [comment]
ok,i put all of the files into the folder I made in the Wii U  then apps folder on the sd card. I put all the files in the HB AppStore master folder (most recent files) and it isn't popping up on homebrew I also using that type of homebrew. I think its because there is no .elf file.

**Comment by vgmoose** [comment]
The HBL 1.4 should be able to run rpx files. Can you send a screen shot of the /wiiu/apps folder?

Latest HBL is here: https://apps.fortheusers.org/wiiu/homebrew_launcher

**Comment by BlaklavaFx** [comment]
I have HBL 1.4, it cant run .rpx files. also in my /wiiu/apps folder, there's the folder named "AppStore" then all of the files of the hb-AppStore are in there. So I don't know why it isn't working to load the .rpx files.

**Comment by vgmoose** [comment]
I think that issues like this is are one reason I made the app store in the first place 😄 

[this file](https://github.com/vgmoose/hb-appstore/releases/download/2.2/wiiu-extracttosd.zip) should be extracted to the root of the SD card. Is this right? Can I see a screen shot of your setup on the SD card?

**Comment by BlaklavaFx** [comment]
Sorry, but I can't make a photo of my sd card but what I can say, is that the most recent appstore doesnt have the .rpx. the file you sent me has a .rpx and i can load it. so yeah help.

**Comment by vgmoose** [comment]
Where are you not seeing an RPX?

The build I linked is the most recent appstore, from the [releases page](https://github.com/vgmoose/hb-appstore/releases/)

**Comment by BlaklavaFx** [comment]
ok I found he .rpx, and I loaded it but now it won't download uninstall redownload or download help

**Comment by vgmoose** [comment]
Does it connect to the Internet?

If yes, does it list apps to install?

If yes, what happens when you try to download them?

Can you double check that your SD card write lock isn't flipped. It's a physical switch on the card that looks like [this](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Ftechiedan.com%2Fwp-content%2Fuploads%2F2014%2F04%2FSD-Card-lock.jpg&f=1&nofb=1).

**Comment by BlaklavaFx** [comment]
fixed From: vgmooseSent: Friday, June 26, 2020 2:34 PMTo: vgmoose/hb-appstoreCc: BlaklavaFx; AuthorSubject: Re: [vgmoose/hb-appstore] Wii U | App not popping up on homebrew. (#63) Where are you not seeing an RPX?The build I linked is the most recent appstore, from the releases page—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vgmoose** [comment]
The original issue here is fixed, if it's still having issues with downloading, see #42 or you provide an update here
