### ISSUE TITLE
When I load "appstore.rpx",my WiiU freeze!

### ISSUE THREAD

**Issue by Ropyle** [fortheusers/hb-appstore#67]
**Describe the bug**

**Platform:**
Are you using Switch, Wii U, or PC version?

**To Reproduce**
Please provide steps to reproduce the behavior, and what the expected behavior is. If applicable, add screenshots to help explain your problem.

**Comment by Ropyle** [comment]
When I push "load" button (HB App store
![WIN_20201103_15_26_32_Pro](https://user-images.githubusercontent.com/73871264/97955297-347b1880-1de9-11eb-8b6b-66ff37358101.jpg)
) , my WiiU freeze.

**Comment by Ropyle** [comment]
This is my files in SD Card.
[Uploading sd.zip…]()

**Comment by Ropyle** [comment]
sd/wiiu/apps/appstore.rpx
sd/wiiu/apps/icon.png
sd/wiiu/apps/meta.xml
sd/wiiu/551hbl.mp4

I put folders.

**Comment by Ropyle** [comment]
I could loaded HB Appstore.rpx by "the Homebrew launcher".

**Comment by vgmoose** [comment]
you’re saying updating HBL worked?
