### ISSUE TITLE
Apps don't work

### ISSUE THREAD

**Issue by Arbifoxx** [fortheusers/hb-appstore#68]
**Describe the bug**
When I download or update the apps, no matter what I do, the apps ALWAYS crash. Also, the further down I scroll, eventually, the GUI stops working (I think its the GUI)

**Platform:**
Wii U

**To Reproduce**
Install an app, launch it, done.

**Comment by compucat** [comment]
Please provide more information. Are you running the latest version of HBAS?

What version of the Homebrew Launcher are you using? How are you launching it? What apps have you tested?

GUI issues sound like the most likely candidate for an HBAS/Chesto bug; can you take a video documenting this and link it here?

**Comment by vgmoose** [comment]
^ all of the above, closing for now
