### ISSUE TITLE
aio-switch-updater can't be updated or installed

### ISSUE THREAD

**Issue by hrvylein** [fortheusers/hb-appstore#70]
**Describe the bug**
aio-switch-updater can't be updated or installed

**Platform:**
Switch, atm 0.19.0 on 12.0.0

**To Reproduce**
Try to install aio-switch-updater, it hangs an infinite time on downloading (100% filled blue bar), but it never actually installs. Zip file is created in tmp. Manually deleting the registry files in .get doesn't help either. Other apps like ldn_mitm updated just fine without a problem.

**Comment by vgmoose** [comment]
Seems like an issue with that specific zip file for some reason. @pwsincd updated the file to one that is not exactly the same, does it still have the same problem?

Attached is the previous file:
[aioswitchupdater.zip 10-34-01-553.zip](https://github.com/fortheusers/hb-appstore/files/6360744/aioswitchupdater.zip.10-34-01-553.zip)

When downloading on PC it extracts and downloads fine. Probably a test repo should be set up and this debugged on the Switch to see what happens during the download/extract. We have seen this issue once before with a specific version of the Turnips app almost exactly a year ago (week of 4/24/20).

**Comment by hrvylein** [comment]
It installs now. :)
