### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FieryMewtwo** [fortheusers/hb-appstore#71]
Does this require CFW on O3DS?

**Comment by Masamune3210** [comment]
yes, any homebrew requires cfw

**Comment by FieryMewtwo** [comment]
since when?

**Comment by Masamune3210** [comment]
Everything moved to Roselina and the new hax model a while ago, there is literally almost no reason to not install Luma at this point

**Comment by compucat** [comment]
@FieryMewtwo: There is no official 3DS build of the Homebrew App Store at this time; we're working on getting things ready for release.
