### ISSUE TITLE
Ftpd 3.1.0 only downloads classic, not both

### ISSUE THREAD

**Issue by OrGoN3** [fortheusers/hb-appstore#74]
**Package:**
Which app or package on the Store is giving you trouble?
Ftpd by mtheall
**Describe the problem**
A clear and concise description of what the problem is.
Previously this would install both the classic and gui version of ftpd. Now, since 3.1.0, it only installs the classic. It also removed the 3.0 gui I had.
**Platform:**
Is this for the Switch, Wii U, or both versions? Switch

The page still says it'll download both versions. This probably was simply overlooked.

**Comment by Troy2424** [comment]
I have the same problem, it's annoying, wish they would just separate them so we can download just one or the other.

**Comment by pwsincd** [comment]
included both packages in the download..  please redownload.
