### ISSUE TITLE
Better indicator when offline

### ISSUE THREAD

**Issue by vgmoose** [fortheusers/hb-appstore#9]
While offline, the progress bar just never loads on the loading screen. Ideally this would display a message instructing the user to connect to the internet.

Additionally. if it disconnects while at the app listing screen, the Download button just dismisses the popup. A similar check should be placed there.

**Comment by ImmaSpoon** [comment]
I have created a simple animation that I think looks pretty cool: [Here it is](https://i.imgur.com/rkW5JPY.gif)

**Comment by vgmoose** [comment]
Internet onnectivity check + troubleshooting added in https://github.com/vgmoose/appstorenx/commit/3b96e39e83602024354eec8f1c84ffb03d0a6a1d

<img width="600" alt="screen shot 2018-08-29 at 2 18 06 am" src="https://user-images.githubusercontent.com/2467473/44892293-e1115b00-acb1-11e8-9fc8-4df8ceb6bb54.png">
    
I haven't put in any icon/animation, but would want to add them at some point.
